# You can specify a custom docker image from Docker Hub as your build environment.
image: jgoldfar/latex-julia-docker:release-latest

pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y make curl git ssh
          - make generate
