# You can specify a custom docker image from Docker Hub as your build environment.
# Use a somewhat-official Docker image (https://github.com/jojomi/docker-hugo)
# to test backup integration
image: jojomi/hugo:latest

pipelines:
  default:
    - step:
        script:
          - hugo --verbose --minify
