# You can specify a custom docker image from Docker Hub as your build environment.
image: jgoldfar/latex-docker:plus-julia-release-latest

pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y make curl mercurial rsync git
          - make pull-deps push-git
