# You can specify a custom docker image from Docker Hub as your build environment.
image: debian:12.2-slim
pipelines:
  default:
    - step:
        script:
          # https://packages.debian.org/search?suite=bookworm&keywords=...
          - apt-get -qq update && apt-get -qq -y install shellcheck build-essential curl inkscape git
          - make hugo-env
          - git submodule update --recursive --init
          - make generate
