baseURL = "https://jgoldfar.github.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "jgoldfar's home on the web"
metaDataFormat = "yaml"

[params]
    font = "Raleway" # should match the name on Google Fonts!
    fontAlternate = "Oswald"
    authorName="Jonathan Goldfarb"
    authorOffice="MAC, Quad 405"
    authorPhone="321 674-8157"
    authorEmail="jgoldfar@my.fit.edu"

[[menu.sidebar]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.sidebar]]
    name = "CV"
    weight = 2
    identifier = "cv"
    url = "/media/cv.pdf"

[[menu.sidebar]]
    name = "Courses"
    weight = 3
    identifier = "courses"
    url = "/course"

[[menu.sidebar]]
    name = "Research"
    weight = 3
    identifier = "research"
    url = "/research"

[[menu.sidebar]]
    name = "Presentations"
    weight = 1
    identifier = "presentations"
    url = "/presentations"

[[menu.sidebar]]
    name = "Schedule"
    weight = 1
    identifier = "schedule"
    url = "/schedule"