baseURL = "https://jgoldfar.github.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "jgoldfar's home on the web"
metaDataFormat = "yaml"
enableGitInfo = false # TODO: make this a git repo, enable
paginate = 5
disqusShortname = jgoldfar-blog

[taxonomies]
    tags = "tags"

[params]
    font = "Raleway" # should match the name on Google Fonts!
    fontAlternate = "Oswald"
    authorName="Jonathan Goldfarb"
    authorImage="https://raw.githubusercontent.com/jgoldfar/jgoldfar.github.io/master/media/img/max.jpg"
    authorMisc="Applied Mathematician"
    authorOffice="MAC, Quad 405"
    authorPhone="321 674-8157"
    authorEmail="jgoldfar@my.fit.edu"
    authorGithub="https://github.com/jgoldfar"
    authorGitlab="https://gitlab.com/jgoldfar"
    authorBitbucket="https://bitbucket.org/jgoldfar/"
    authorResearchGate="https://www.researchgate.net/profile/Jonathan_Goldfarb"

## sidebar for main page
[[menu.sidebar]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.sidebar]]
    name = "CV"
    weight = 2
    identifier = "cv"
    url = "/cv/cv.pdf"

[[menu.sidebar]]
    name = "Teaching"
    weight = 3
    identifier = "teaching"
    url = "/teaching"

[[menu.sidebar]]
    name = "Research"
    weight = 3
    identifier = "research"
    url = "/research"

[[menu.sidebar]]
    name = "Presentations"
    weight = 4
    identifier = "presentations"
    url = "/presentations"

[[menu.sidebar]]
    name = "Schedule"
    weight = 2
    identifier = "schedule"
    url = "/schedule"

## sidebar for Blog
[[menu.sidebarBlog]]
    name = "Home"
    weight = 4
    identifier = "home"
    url = "/"

[[menu.sidebarBlog]]
    name = "Blog Home"
    weight = 1
    identifier = "blogIndex"
    url = "/blog"

[[menu.sidebarBlog]]
    name = "About"
    weight = 2
    identifier = "about"
    url = "/blog/about/"

[[menu.sidebarBlog]]
    name = "CV"
    weight = 2
    identifier = "cv"
    url = "/cv/cv.pdf"

[[menu.sidebarBlog]]
    name = "Software"
    weight = 2
    identifier = "software"
    url = "/oss-contributions/"

## Course list for homepage
[[menu.courses]]
    name = "MTH 1001: Calculus 1"
    weight = 1
    identifier = "mth1001"
    url = "/teaching/mth1001"
