baseURL = "https://jgoldfar.github.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "intentional chaos"
metaDataFormat = "yaml"
enableGitInfo = true
paginate = 20
disqusShortname = "jgoldfar-blog"

theme = "hugo-coder"

pygmentsCodeFences = true
pygmentsOptions = "nobackground=True"
pygmentsStyle = "emacs"
pygmentsCodefencesGuessSyntax = true


# https://github.com/luizdepra/hugo-coder/wiki/Configurations
[params]
    author = "Jonathan Goldfarb, Ph.D."
    info = "Mathematics and Technical Problem Analysis"
    description = "Jonathan Goldfarb Online"
    keywords = "blog,mathematics,software,personal"
    avatarurl = "https://raw.githubusercontent.com/jgoldfar/jgoldfar.github.io/master/media/img/max.jpg"
	# gravatarurl = "jgoldfar@gmail.com"

    # favicon_32 = "/img/favicon-32x32.png"
    # favicon_16 = "/img/favicon-16x16.png"

    footercontent = "solve the world"

	dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = false
    since = 2018

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://bitbucket.org/jgoldfar/personal-site-git/commits"

    rtl = false

    math = true

	# Custom CSS
    custom_css = []

	# Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    # colorscheme = "auto"

	# Custom JS
    custom_js = []

# Setup taxonomies
[taxonomies]
	category = "categories"
    tags = "tags"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 2
    url = "https://github.com/jgoldfar/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/jgoldfar/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/jgoldfar/"
# [[params.social]]
    # name = "Bitbucket"
    # icon = "fab fa-bitbucket fa-2x"
    # weight = 3
    # url = "https://bitbucket.org/jgoldfar/"
# [[params.social]]
    # name = "ResearchGate"
    # icon = "fab fa-researchgate fa-2x"
    # weight = 5
    # url = "https://www.researchgate.net/profile/Jonathan_Goldfarb"
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope fa-2x"
    weight = 1
    url = "mailto:jgoldfar@my.fit.edu"
[[params.social]]
    name = "Phone"
    icon = "fas fa-phone fa-2x"
    weight = 5
    url = "tel:+1-321-895-4184"
[[params.social]]
    name = "Physical (By Appointment, Send Email!)"
    icon = "fas fa-map-marker-alt fa-2x"
    weight = 5
    url = "https://goo.gl/maps/RQbuqrKWfhPenAX27"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 5
    url = "https://www.linkedin.com/in/jonathan-goldfarb-8684851b/"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 6
    url = "https://jgoldfar.github.io/index.xml"
    rel = "alternate"
    type = "application/rss+xml"
# [[params.social]]
    # name = "Docjer Hub"
    # icon = "fab fa-docker"
    # weight = 5
	# url = "https://hub.docker.com/u/jgoldfar/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url  = "/projects/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
# [[menu.main]]
    # name = "CV"
    # weight = 4
    # identifier = "cv"
    # url = "/cv/cv.pdf"

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
    # siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    # serverURL = "analytics.example.com"

# [[menu.sidebar]]
#     name = "Teaching"
#     weight = 3
#     identifier = "teaching"
#     url = "/teaching"

# [[menu.sidebar]]
#     name = "Research"
#     weight = 3
#     identifier = "research"
#     url = "/research"

# [[menu.sidebar]]
#     name = "Presentations"
#     weight = 4
#     identifier = "presentations"
#     url = "/presentations"

# [[menu.sidebar]]
#     name = "Schedule"
#     weight = 2
#     identifier = "schedule"
#     url = "/schedule"

# [[menu.sidebar]]
#     name = "Blog"
#     weight = 2
#     identifier = "blog"
#     url = "/blog"

# ## sidebar for Blog
# [[menu.sidebarBlog]]
#     name = "Home"
#     weight = 4
#     identifier = "home"
#     url = "/"

# [[menu.sidebarBlog]]
#     name = "Blog Home"
#     weight = 1
#     identifier = "blogIndex"
#     url = "/blog"

# [[menu.sidebarBlog]]
#     name = "About"
#     weight = 2
#     identifier = "about"
#     url = "/blog/about/"

# [[menu.sidebarBlog]]
#     name = "CV"
#     weight = 2
#     identifier = "cv"
#     url = "/cv/cv.pdf"

# [[menu.sidebarBlog]]
#     name = "Software"
#     weight = 2
#     identifier = "software"
#     url = "/oss-contributions/"

# ## Course list for homepage
# [[menu.courses]]
#     name = "MTH 4101: Mathematical Modeling"
#     weight = 1
#     identifier = "mth4101"
#     url = "/projects/mathmodeling"
