baseURL = "https://jgoldfar.github.io"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
title = "Jonathan Goldfarb"
metaDataFormat = "yaml"
enableGitInfo = true
paginate = 20
# Enable comments by entering your Disqus shortname
disqusShortname = "jgoldfar-blog"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

theme = "universal"

pygmentsCodeFences = true
pygmentsOptions = "nobackground=True"
pygmentsStyle = "emacs"
pygmentsCodefencesGuessSyntax = true


# https://github.com/luizdepra/hugo-coder/wiki/Configurations
[params]
    # viewMorePostLink = "/blog/"
    author = "Jonathan Goldfarb, Ph.D."
    info = "Intention, Collaboration, Innovation"
    defaultDescription = "Jonathan Goldfarb, Online."
    keywords = "blog,personal,technology"
    avatarurl = "https://raw.githubusercontent.com/jgoldfar/jgoldfar.github.io/master/img/max.jpg"
    # gravatarurl = "jgoldfar@gmail.com"
    # mainSections = ["blog"]

    twitter_site = "jgoldfar" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/logo.png"

    footercontent = "Amor Fati"

    date_format = "January 2, 2006"

    hideCredits = true
    hideCopyright = false
    since = 2018

    # https://en.wikiquote.org/wiki/Voltaire
    about_us = "<p>Quoi que vous fassiez, écrasez l'infâme, et aimez qui vous aime. - Voltaire</p><p>Always open to challenging new problems.</p>"
    copyright = "Copyright (c) 2018 - 2021, Jonathan Goldfarb; all rights reserved."
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    latitude = "-12.043333"
    longitude = "-77.028333"
    direction = "Desaperacidos"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p class='text-uppercase'><strong>Jonathan Goldfarb</strong>
        <br />Bend, OR</p>"""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/jgoldfar/jgoldfar.github.io/commit/"
    # commit = "https://bitbucket.org/jgoldfar/personal-site-git/commits"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/f/mjvpnqkl"
    contact_form_ajax = false

    rtl = false

    math = true

	# Custom CSS
    custom_css = []

	# Custom JS
    custom_js = []

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Setup taxonomies
[taxonomies]
	category = "categories"
    tags = "tags"

# Enable or disable top bar with social icons
# Share Your Requirements.
[params.topbar]
    enable = true
    text = """
         <p class='hidden-sm hidden-xs'>Always Open.
            <a href='mailto:jgoldfar@gmail.com' data-animate-hover='pulse'><i class='fas fa-envelope'></i> jgoldfar (at) gmail (dot) com</a>
         </p>
         <p class='hidden-md hidden-lg'>
            <a href='tel:1-321-895-4184' data-animate-hover='pulse'><i class='fas fa-phone'></i> +1 (321) 895-4184</a>
            <a href='mailto:jgoldfar@gmail.com' data-animate-hover='pulse'><i class='fas fa-envelope'></i> jgoldfar (at) gmail (dot) com</a>
         </p>"""

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Clients"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From the blog"
    subtitle = ""

# Social links for top bar
[[menu.topbar]]
    name = "LinkedIn"
    pre = "<i class='fab fa-linkedin fa-2x'></i>"
    weight = 1
    url = "https://www.linkedin.com/in/jonathan-goldfarb/"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/jgoldfar"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Gitlab"
    url = "https://gitlab.com/jgoldfar/"
    pre = "<i class='fab fa-2x fa-gitlab'></i>"

[[menu.topbar]]
    weight = 6
    name = "Twitter"
    url = "https://twitter.com/jgoldfar/"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:jgoldfar@gmail.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[[menu.topbar]]
    name = "Phone"
    pre = "<i class='fas fa-phone fa-2x'></i>"
    weight = 4
    url = "tel:+1-321-895-4184"

# [[params.social]]
    # name = "ResearchGate"
    # icon = "fab fa-researchgate fa-2x"
    # weight = 5
    # url = "https://www.researchgate.net/profile/Jonathan_Goldfarb"
# [[params.social]]
    # name = "Google Scholar"
    # icon = "fab fa-... fa-2x"
    # weight = 5
    # url = "https://..."
# [[params.social]]
#     name = "Physical (By Appointment, Send Email!)"
#     icon = "fas fa-map-marker-alt fa-2x"
#     weight = 5
#     url = "https://goo.gl/maps/RQbuqrKWfhPenAX27"

[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 6
    url = "https://jgoldfar.github.io/index.xml"
    rel = "alternate"
    type = "application/rss+xml"
# [[params.social]]
    # name = "Docker Hub"
    # icon = "fab fa-docker"
    # weight = 5
	# url = "https://hub.docker.com/u/jgoldfar/"

# Menu links
# [[menu.main]]
#     name = "Blog"
#     weight = 1
#     url  = "/posts/"
# # [[menu.main]]
#     name = "Projects"
#     weight = 2
#     url  = "/projects/"
[[menu.main]]
    name = "About"
    weight = 1
    url = "/contact"
# # [[menu.main]]
    # name = "CV"
    # weight = 4
    # identifier = "cv"
    # url = "/cv/cv.pdf"
