RSYNC=rsync -a
UNAME=$(shell uname -s)
HUGO?=bin/hugo

ifeq ($(UNAME),Darwin)
$(HUGO): bin/hugo_0.40.3_macOS-64bit.tar.gz
	cd bin && tar xvzf $(notdir $<)
endif

ifeq ($(UNAME),Linux)
$(HUGO): bin/hugo_0.40.3_Linux-64bit.tar.gz
	cd bin && tar xvzf $(notdir $<)
endif

### Dependencies
pull-deps: reading-group-deps


ARGDownloadPath=https://bitbucket.org/jgoldfar/algebrareadinggroupnotes/downloads
ARGCoursePath=static/AlgebraReadingGroup
ARGFiles=hersteinExercises.pdf munkresExercises.pdf index.htm
InstallDirs+=$(ARGCoursePath)

reading-group-deps:
	mkdir -p $(ARGCoursePath)
	$(foreach file, $(ARGFiles), \
		curl -L "$(ARGDownloadPath)/$(file)" -o "$(ARGCoursePath)/$(file)"; \
	)

CVCloneDir=deps/CV
CloneDirs+=$(CVCloneDir)
CVFSPath=../../../misc/resume
CVPath=static/cv
InstallDirs+=$(CVPath)
CVFiles=cv.pdf res.pdf
update-cv:
	mkdir -p $(CVCloneDir)
	hg clone $(CVFSPath) $(CVCloneDir) || hg pull --cwd $(CVCloneDir)
	hg update --cwd $(CVCloneDir)
	$(MAKE) -C $(CVCloneDir) $(CVFiles)
	mkdir -p $(CVPath)
	$(foreach file, $(CVFiles), \
		mv $(CVCloneDir)/$(file) "$(CVPath)/$(file)"; \
	)

$(addprefix $(CVPath),$(CVFiles)): update-cv

HUGOFILE := config.toml

serve: $(HUGOFILE) $(HUGO)
	$(HUGO) --verbose server

### Generate site
GitRepoName=jgoldfar.github.io
gen-git: $(HUGOFILE) $(HUGO)
	$(HUGO) --verbose
	echo "moving public/ to $(GitRepoName) subdirectory."
	$(RSYNC) ./public/* ./$(GitRepoName)/

init-git:
	if [[ ! -d $(GitRepoName) ]] ; then
	git clone git@github.com:jgoldfar/$(GitRepoName).git
	fi

push-git: gen-git init-git
	git commit -C ./$(GitRepoName) -am "Update with changes generated by hg commit $(shell hg log --limit 1 -T '{node}')"
	git -C ./$(GitRepoName) push

clean:
	$(RM) -r public
	$(RM) -r $(InstallDirs)
	$(RM) -r $(CloneDirs)
	$(RM) -r jgoldfar.github.io
	$(RM) bin/hugo bin/LICENSE bin/README.md
