RSYNC=rsync -a
UNAME=$(shell uname -s)
HUGO?=bin/hugo

ifeq ($(UNAME),Darwin)
$(HUGO): bin/hugo_0.40.3_macOS-64bit.tar.gz
	cd bin && tar xvzf $(notdir $<)
endif

ifeq ($(UNAME),Linux)
$(HUGO): bin/hugo_0.40.3_Linux-64bit.tar.gz
	cd bin && tar xvzf $(notdir $<)
endif

site.yaml-old: site.yaml
	cp $< $@

### Dependencies
pull-deps: reading-group-deps cv-deps


ARGCloneDir=deps/AlgebraReadingGroup
CloneDirs+=$(ARGLocalDir)
ARGFSPath=../../AlgebraReadingGroup
ARGCoursePath=static/AlgebraReadingGroup
InstallDirs+=$(ARGCoursePath)
reading-group-deps:
	mkdir -p $(ARGCloneDir)
	hg clone $(ARGFSPath) $(ARGCloneDir) || hg pull --cwd $(ARGCloneDir)
	hg update --cwd $(ARGCloneDir)
	$(MAKE) -C $(ARGCloneDir) hersteinExercises.pdf munkresExercises.pdf
	mkdir -p $(ARGCoursePath)
	cp $(ARGCloneDir)/hersteinExercises.pdf $(ARGCoursePath)/hersteinExercises.pdf
	cp $(ARGCloneDir)/munkresExercises.pdf $(ARGCoursePath)/munkresExercises.pdf
	cp $(ARGCloneDir)/index.htm $(ARGCoursePath)/index.htm

CVCloneDir=deps/CV
CloneDirs+=$(CVCloneDir)
CVFSPath=../../../misc/resume
CVPath=static/cv
InstallDirs+=$(CVPath)
CVFiles=cv.pdf res.pdf res_statement.pdf teach_statement.pdf
cv-deps:
	mkdir -p $(CVCloneDir)
	hg clone $(CVFSPath) $(CVCloneDir) || hg pull --cwd $(CVCloneDir)
	hg update --cwd $(CVCloneDir)
	$(MAKE) -C $(CVCloneDir) $(CVFiles)
	mkdir -p $(CVPath)
	cp $(CVCloneDir)/*.pdf $(CVPath)

### Push targets
gen-git: config.toml pull-deps $(HUGO)
	$(HUGO) --verbose
	echo "moving public/ to jgoldfar.github.io subdirectory."
	$(RSYNC) ./public/* ./jgoldfar.github.io/

push-git: gen-git
	-cd ./jgoldfar.github.io && git commit -am "Update with changes generated by hg commit $(shell hg log --limit 1 -T '{node}')"
	-cd ./jgoldfar.github.io && git push

clean:
	$(RM) -r deploy
	$(RM) -r $(ARGCoursePath)
	$(RM) -r $(ARGLocalDir)
	$(RM) -r $(addprefix content/media/,$(CVFiles))
