#!/bin/sh
echo `pwd`
#cd `dirname $0`
#echo `dirname $0`
#echo `pwd`

cp site.yaml site.yaml-old
cp github.site.yaml site.yaml
hyde gen
rm site.yaml
cp site.yaml-old site.yaml

echo "moving deploy/ to jgoldfar.github.io subdirectory."
cp -a ./deploy/* ./jgoldfar.github.io/

cd ./jgoldfar.github.io && \
  git commit -m "Update with changes generated upstream" && \
  git push
