#!/bin/sh

cp site.yaml site.yaml-bak
cp site.yaml-github.io site.yaml
hyde gen
cp site.yaml-bak site.yaml

cp -r deploy/* jgoldfar.github.io
mv jgoldfar.github.io/index.htm jgoldfar.github.io/index.html

cd jgoldfar.github.io
ctime=$(date +"%c")
echo "Commiting mercurial/hg-git subrepo"
echo $ctime
hg ci -m "Update to site as of $ctime"

echo "Pushing to github.io"
hg push
