mode: development
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
base_url: jgoldfar.github.io # The base url for autogenerated links. # /~jgoldfar # /Users/jgoldfar/Documents/work/projects/personal-site/deploy
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.meta.AutoExtendPlugin
    
meta:
    nodemeta: meta.yaml
    created: !!timestamp 2013-10-27 00:00:00
    author: Jonathan Goldfarb