Busy-Hours-Julia.png: example.jl Project.toml Swipes-Time-Only.csv
	julia --project=. $<

Busy-Hours-R.png: example.R Swipes-Time-Only.csv
	Rscript $<

Busy-Hours-Python.png: example.py Swipes-Time-Only.csv
	pythonw $<
