name: Build Hugo site using Github pages
# Demo script from https://gohugo.io/hosting-and-deployment/hosting-on-github/
on:
  push:
  schedule:
    - cron: '30 5 * * 2,4'


jobs:
  deploy:
    name: Deploy https://jgoldfar.github.io
    strategy:
      fail-fast: false
      matrix:
        platform: ['ubuntu-slim', 'ubuntu-24.04']
    runs-on: ${{ matrix.platform }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout the repository to generate the site
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 1    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo version
        run: |
          make hugo-env

      - name: Build with Hugo, output version
        run: |
          hugo version
          hugo --minify --panicOnWarning

      - name: Deploy
        uses: peaceiris/actions-gh-pages@f4984ce547e7de88896c1d092ae7e008fed5ba31 # v4
        if: (github.ref == 'refs/heads/main' && matrix.platform == 'ubuntu-24.04')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
