name: Build Hugo site using Github pages
# Demo script from https://gohugo.io/hosting-and-deployment/hosting-on-github/
on:
  push:
  schedule:
    - cron: '30 5 * * 2,4'


jobs:
  deploy:
    name: Deploy https://jgoldfar.github.io
    strategy:
      fail-fast: false
      matrix:
        platform: ['ubuntu-slim', 'ubuntu-24.04']
    runs-on: ${{ matrix.platform }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Checkout the repository to generate the site
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 1    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo version
        run: |
          make hugo-env

      - name: Build with Hugo
        run: |
          make generate-min

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@98ef48e41587a300b82de4cf298aa98b57b2faae # v5.0.0
        if: (github.ref == 'refs/heads/main' && matrix.platform == 'ubuntu-24.04')
        with:
          path: public

      - name: Deploy
        if: (github.ref == 'refs/heads/main' && matrix.platform == 'ubuntu-24.04')
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v4
